insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AD', 'Andorra', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AE', 'Emiratos Árabes Unidos', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AF', 'Afganistán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AG', 'Antigua y Barbuda', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AI', 'Anguila', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AL', 'Albania', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AM', 'Armenia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AN', 'Antillas Neerlandesas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AO', 'Angola', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AQ', 'Antártida', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AR', 'Argentina', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AS', 'Samoa Americana', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AT', 'Austria', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AU', 'Australia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AW', 'Aruba', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('AZ', 'Azerbaiyán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BA', 'Bosnia y Hercegovina', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BB', 'Barbados', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BD', 'Bangladesh', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BE', 'Bélgica', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BF', 'Burkina Faso', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BG', 'Bulgaria', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BH', 'Bahráin', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BI', 'Burundi', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BJ', 'Benín', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BM', 'Bermudas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BN', 'Brunéi', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BO', 'Bolivia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BR', 'Brasil', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BS', 'Bahamas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BT', 'Bután', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BV', 'Isla Bouvet', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BW', 'Botsuana', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BY', 'Bielorrusia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('BZ', 'Belice', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CA', 'Canadá', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CC', 'Islas Cocos', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CD', 'República Democrática del Congo', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CF', 'República Centroafricana', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CG', 'Congo', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CI', 'Costa de Marfil', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CK', 'Islas Cook', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CL', 'Chile', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CM', 'Camerún', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CN', 'China', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CO', 'Colombia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CR', 'Costa Rica', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CU', 'Cuba', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CV', 'Cabo Verde', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CX', 'Isla Christmas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CY', 'Chipre', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CZ', 'República Checa; Chequia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('CH', 'Suiza', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('DE', 'Alemania', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('DJ', 'Yibuti', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('DK', 'Dinamarca', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('DM', 'Dominica', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('DO', 'República Dominicana', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('DZ', 'Argelia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('EC', 'Ecuador', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('EE', 'Estonia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('EG', 'Egipto', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('EH', 'Sáhara Occidental', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ER', 'Eritrea', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ES', 'España', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ET', 'Etiopía', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('FI', 'Finlandia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('FJ', 'Fiyi', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('FK', 'Islas Malvinas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('FM', 'Micronesia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('FO', 'Islas Feroe', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('FR', 'Francia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GA', 'Gabón', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GB', 'Reino Unido', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GD', 'Granada', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GE', 'Georgia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GF', 'Guayana Francesa', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GH', 'Ghana', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GI', 'Gibraltar', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GL', 'Groenlandia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GM', 'Gambia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GN', 'Guinea', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GP', 'Guadalupe', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GQ', 'Guinea Ecuatorial', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GR', 'Grecia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GS', 'Islas Georgia del Sur y Sandwich del Sur', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GT', 'Guatemala', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GU', 'Guam', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GW', 'Guinea-Bissau', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('GY', 'Guyana', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('HM', 'Islas Heard y McDonald', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('HN', 'Honduras', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('HR', 'Croacia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('HT', 'Haití', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('HU', 'Hungría', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ID', 'Indonesia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('IE', 'Irlanda', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('IL', 'Israel', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('IN', 'India', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('IO', 'Territorio Británico del Océano Índico', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('IQ', 'Iraq', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('IR', 'Irán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('IS', 'Islandia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('IT', 'Italia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('JM', 'Jamaica', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('JO', 'Jordania', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('JP', 'Japón', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KE', 'Kenia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KG', 'Kirguizistán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KH', 'Camboya', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KI', 'Kiribati', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('UY', 'Uruguay', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('UZ', 'Uzbekistán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('VA', 'El Vaticano', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('VC', 'San Vicente y las Granadinas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('VE', 'Venezuela', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('VG', 'Islas Vírgenes Británicas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('VI', 'Islas Vírgenes Americanas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('VN', 'Vietnam', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('VU', 'Vanuatu', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('WF', 'Wallis y Futuna', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('WS', 'Samoa', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('YE', 'Yemen', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('YT', 'Mayotte', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('YU', 'Serbia y Montenegro', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ZA', 'Sudáfrica', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ZM', 'Zambia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ZW', 'Zimbabue', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KM', 'Comoras', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KN', 'San Cristóbal y Nieves', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KP', 'Corea del Norte', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KR', 'Corea del Sur', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KW', 'Kuwait', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KY', 'Islas Caimán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('KZ', 'Kazajistán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LA', 'Laos', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LB', 'Líbano', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LC', 'Santa Lucía', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LI', 'Liechtenstein', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LK', 'Sri Lanka', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LR', 'Liberia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LS', 'Lesoto', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LT', 'Lituania', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LU', 'Luxemburgo', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LV', 'Letonia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('LY', 'Libia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MA', 'Marruecos', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MC', 'Mónaco', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MD', 'Moldavia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MG', 'Madagascar', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MH', 'Islas Marshall', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MK', 'Macedonia; Antigua República Yugoslava de Macedonia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ML', 'Malí', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MM', 'Birmania; Myanmar', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MN', 'Mongolia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MO', 'Macao', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MP', 'Islas Marianas del Norte', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MQ', 'Martinica', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MR', 'Mauritania', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MS', 'Montserrat', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MT', 'Malta', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MU', 'Mauricio', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MV', 'Maldivas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MW', 'Malaui', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MX', 'México', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MY', 'Malasia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('MZ', 'Mozambique', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NA', 'Namibia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NC', 'Nueva Caledonia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NE', 'Níger', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NF', 'Isla Norfolk', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NG', 'Nigeria', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NI', 'Nicaragua', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NL', 'Países Bajos', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NO', 'Noruega', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NP', 'Nepal', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NR', 'Nauru', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NU', 'Niue', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('NZ', 'Nueva Zelanda', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('OM', 'Omán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PA', 'Panamá', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PE', 'Perú', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PF', 'Polinesia Francesa', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PG', 'Papúa-Nueva Guinea', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PH', 'Filipinas', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PK', 'Pakistán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PL', 'Polonia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PM', 'San Pedro y Miquelón', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PN', 'Islas Pitcairn', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PR', 'Puerto Rico', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PT', 'Portugal', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PW', 'Palaos', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('PY', 'Paraguay', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('QA', 'Qatar', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('RE', 'Reunión', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('RO', 'Rumania; Rumanía', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('RU', 'Rusia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('RW', 'Ruanda', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SA', 'Arabia Saudí', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SB', 'Islas Salomón', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SC', 'Seychelles', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SD', 'Sudán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SE', 'Suecia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SG', 'Singapur', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SH', 'Santa Helena', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SI', 'Eslovenia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SJ', 'Svalbard y Jan Mayen', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SK', 'Eslovaquia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SL', 'Sierra Leona', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SM', 'San Marino', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SN', 'Senegal', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SO', 'Somalia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SR', 'Surinam', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('ST', 'Santo Tomé y Príncipe', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SV', 'El Salvador', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SY', 'Siria', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('SZ', 'Suazilandia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TC', 'Islas Turcas y Caicos', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TD', 'Chad', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TF', 'Territorios Australes Franceses', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TG', 'Togo', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TH', 'Tailandia', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TJ', 'Tayikistán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TK', 'Tokelau', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TL', 'Timor Oriental', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TM', 'Turkmenistán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TN', 'Túnez', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TO', 'Tonga', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TR', 'Turquía', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TT', 'Trinidad y Tobago', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TV', 'Tuvalu', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TW', 'Taiwán', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('TZ', 'Tanzania', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('UA', 'Ucrania', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('UG', 'Uganda', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('UM', 'Islas menores alejadas de los Estados Unidos', null, '');
insert into likees_country (ID, NAME_DEFAULT_M, NAME_CODE_M, FLAG_URL) values ('US', 'Estados Unidos', null, '');